### ISSUE TITLE
Microsoft Edge and IE support

### ISSUE THREAD

**Issue by bruklig** [davejm/compress.js#3]
Hey David!

Thank you for your library, It works really good.

Just wanted to let you know that it doesn't work in Microsoft Edge browser. I've tried the demo as well https://davidmoodie.com/client-compress/ . Nothing happens when you upload the image. Browser console is empty. No errors or warnings.

Any idea how to fix it maybe? Or any plans to add MS Edge or IE support?

Thank you!

Rustam.

**Comment by tet-web-dev** [comment]
Did you find a fix @bruklig ? Maybe it will work on the new edge chromium.

**Comment by yesworld** [comment]
You can add [JavaScript-Canvas-to-Blob](https://github.com/blueimp/JavaScript-Canvas-to-Blob) before **client-compress**. It will help only MS Edge in IE doens't work..
I created a plugin [(Images Optimize and Upload CF7)](https://wordpress.org/plugins/images-optimize-and-upload-cf7) for the **WordPress**, using this compress.

**Comment by davejm** [comment]
Sorry, but support for IE/Edge is not a priority for this library. As tet-web-dev suggested, this may work on the new Edge
