### ISSUE TITLE
Exif orientation support broken with iOS 13.4.1 and Safari 13.1 Desktop/Mac

### ISSUE THREAD

**Issue by ssmithereens** [davejm/compress.js#4]
In iOS 13.4.1 (released a few days ago) as well as Safari 13.1 Desktop/Mac, the EXIF orientation value is no longer being handled properly, and the compressed image that is output will not have the correct orientation.

The easiest way to reproduce this is to go to the https://davidmoodie.com/client-compress/ demo site using a Safari or Chome browser on a device running iOS 13.4.1 and attempt to upload the attached image. This image has orientation EXIF value of 3 (rotated 180 degrees). 

The demo page will return the image rendered upside down. However, the same image on a device not running iOS 13.4.1 will return the image rendered with the proper orientation.

![IMG_2119](https://user-images.githubusercontent.com/36458824/79050966-7e0cd780-7bfb-11ea-978d-839b22379334.JPG)

![Browser-on-iPhone-running-ios-13 4 1](https://user-images.githubusercontent.com/36458824/79051036-e5c32280-7bfb-11ea-9924-3c20a303a0a8.PNG)

**Comment by ssmithereens** [comment]
I believe that this change in Webkit (used by Safari) is the source of the problem: https://bugs.webkit.org/show_bug.cgi?id=201123

The required action for this library would be to ignore the EXIF orientation value when on Safari 13.1 (or later).

**Comment by ssmithereens** [comment]
I forked this library at https://github.com/fieldchat/client-compress and created a package @ssmithereens/client-compress

This fork adds a new exifOrientation option that allows you to override the value in the image.

With this new option, you can handle Safari 13.x like this on desktop:

``
if (/Version\/13./.test(navigator.appVersion)) 
     {
            options.exifOrientation = 1
        }
``

**Comment by pranav65** [comment]
Hi there,

I have been using compress.js for single image upload. But, now i want to use this for multiple image uploads.

What i want to achieve is to select multiple image from html input element and then compress it using this library and also preview those compressed images in dynamically generated <img> tag.

like this:- 

`<img id="preview1">
<img id="preview2">
<img id="preview3">`  depending on number of image selected.



This is how i was using it for single image preview and upload

`<input type="file" accept="image/*"   id="image">
<img id="preview">


const options = {
  targetSize: 0.2,
  quality: 0.75,
  maxWidth: 800,
  maxHeight: 600
}

const compress = new Compress(options)
const upload = document.getElementById("image")

upload.addEventListener(
  "change",
  (evt) => {
    const files = [...evt.target.files]
    compress.compress(files).then((conversions) => {
      // Conversions is an array of objects like { photo, info }.
      // 'photo' has the photo data while 'info' contains metadata
      // about that particular image compression (e.g. time taken).

      const { photo, info } = conversions[0]

      console.log({ photo, info })

     // was using this to append to the form data
      newblob = photo.data;

      // Create an object URL which points to the photo Blob data
      const objectUrl = URL.createObjectURL(photo.data)

      // Set the preview img src to the object URL and wait for it to load
      Compress.loadImageElement(preview, objectUrl).then(() => {
        // Revoke the object URL to free up memory
        URL.revokeObjectURL(objectUrl)
      })
    })
  },
  false
)`

i have been trying to achieve it from past 2 days.
i tried to run this in a for loop




`<input type="file" accept="image/*"  multiple  id="image">
<div id="previewdiv"></div>


$(function() {
    
    var imgPreviewUpld = function(input, divId) {

        if (input.files) {
            var numberOfImages = input.files.length;

            for (i = 0; i < numberOfImages; i++) {

                


                $($.parseHTML('<img>')).attr({id : "preview"+i, class:"img-fluid"}).css({"max-height":"200px","max-width":"300px"}).appendTo(divId);




                                const files = [...input.files]
                                                // const files = [evt.files];
                                compress.compress(files).then((conversions) => {
                                // Conversions is an array of objects like { photo, info }.
                                // 'photo' has the photo data while 'info' contains metadata
                                // about that particular image compression (e.g. time taken).

                                const { photo, info } = conversions[0]

                                console.log({ photo, info })

                                //to append to the form data
                                newblob+i = photo.data;
                                // Create an object URL which points to the photo Blob data
                                const objectUrl = URL.createObjectURL(photo.data)

                                // Set the preview img src to the object URL and wait for it to load
                                Compress.loadImageElement(preview+i, objectUrl).then(() => {
                                    // Revoke the object URL to free up memory
                                    // URL.revokeObjectURL(objectUrl)
                                })
                                })                               

            }
                            
                        
                   
                                               
        }

    };

    $('#photoid').on('change', function(evt) {
        imgPreviewUpld(this, 'div.previewdiv');



        
    });
});`
 please help me.

Thanks

**Comment by pranav65** [comment]
hi there,
I have been using [compress.js](https://github.com/fieldchat/client-compress) for single image upload. But, now i want to use this for multiple image uploads.

What i want to achieve is to select multiple image from html input element and then compress it using this library and also preview those compressed images in dynamically generated  tag.

like this:-

  `<img id="preview0">
  <img id="preview1">
  <img id="preview2">`
        ....depending on number of image selected.


 This is how i was using it for single image upload

```
<input type="file" accept="image/*"   id="image">
<img id="preview">
```


```
const options = {
  targetSize: 0.2,
  quality: 0.75,
  maxWidth: 800,
  maxHeight: 600
}

const compress = new Compress(options)
const upload = document.getElementById("image")

upload.addEventListener(
  "change",
  (evt) => {
    const files = [...evt.target.files]
    compress.compress(files).then((conversions) => {
      // Conversions is an array of objects like { photo, info }.
      // 'photo' has the photo data while 'info' contains metadata
      // about that particular image compression (e.g. time taken).

      const { photo, info } = conversions[0]

      console.log({ photo, info })

     // was using this to append to the form data
      newblob = photo.data;

      // Create an object URL which points to the photo Blob data
      const objectUrl = URL.createObjectURL(photo.data)

      // Set the preview img src to the object URL and wait for it to load
      Compress.loadImageElement(preview, objectUrl).then(() => {
        // Revoke the object URL to free up memory
        URL.revokeObjectURL(objectUrl)
      })
    })
  },
  false
)
```

i have been trying to achieve it from past 2 days.
i tried to run this in a for loop

`<input type="file" accept="image/*"  multiple  id="image">
<div id="" class="col previewdiv"></div>`

```
$(function() {
    
    var imgPreviewUpld = function(input, divId) {

        if (input.files) {
            var numberOfImages = input.files.length;

            for (i = 0; i < numberOfImages; i++) {

                


                $($.parseHTML('<img>')).attr({id : "preview"+i, class:"img-fluid"}).css({"max-height":"200px","max-width":"300px"}).appendTo(divId);

                               const options = {
                                    targetSize: 0.2,
                                    quality: 0.75,
                                    maxWidth: 800,
                                    maxHeight: 600
                                        }
                                        const compress = new Compress(options)


                                const files = [...input.files]
                                                // const files = [evt.files];
                                compress.compress(files).then((conversions) => {
                                // Conversions is an array of objects like { photo, info }.
                                // 'photo' has the photo data while 'info' contains metadata
                                // about that particular image compression (e.g. time taken).

                                const { photo, info } = conversions[0]

                                console.log({ photo, info })

                                //to append to the form data
                                newblob+i = photo.data;
                                // Create an object URL which points to the photo Blob data
                                const objectUrl = URL.createObjectURL(photo.data)

                                // Set the preview img src to the object URL and wait for it to load
                                Compress.loadImageElement(preview+i, objectUrl).then(() => {
                                    // Revoke the object URL to free up memory
                                    // URL.revokeObjectURL(objectUrl)
                                })
                                })                               

            }
                            
                        
                   
                                               
        }

    };

    $('#image').on('change', function(evt) {
        imgPreviewUpld(this, 'div.previewdiv');



        
    });
});
```

Please help me. I am a beginner in javascript world but i want to do this for one of my own project.

Thank you

**Comment by amrinderb** [comment]
I fixed this without the need for @ssmithereens fork, and without the need to detect user agents. Actually this problem isn't specific to iOS nor Safari.  Same problem with Chrome 81 (I tested on Windows and Android).  My code here and some more info below.
		
	var supportsExifOrientation = CSS.supports('image-orientation', 'from-image');

	var crop = $('.crop-preview').croppie({
    	viewport: {
      		width: 220,
      		height: 220,
      		type: 'circle'
    	},
    	enableExif: !supportsExifOrientation,
    	enableOrientation: supportsExifOrientation
	});


	var options = {};
	options.url = fileInput; //you should define this yourself

	if (supportsExifOrientation)
		//bugfix don't change orientation
		//since browser displays it correctly natively
		options.orientation = 1;

	crop.croppie('bind', options);

This problem occurs because the latest versions of Chrome and WebKit have decided to natively support exif rotation, fixing a bug that has existed for years requiring libraries like this one to manually rotate the image (i.e. using enableExif option in this library).  Since this problem has been fixed in the latest versions of Chrome etc, it results in an undesired double rotation.  I fixed this in the above code by testing whether the browser supports 'image-rotation' CSS property being set to 'image-orientation', which implies that it will read the exif data and natively rotate accordingly, meaning we don't need to do it ourselves.  If the browser supports it, we set the orientation to 1 so that no rotation is done by the client-compress library, i.e. we allow the browser to read the exif data and display it correctly.

**Comment by Junyan** [comment]
from: https://github.com/Mawi137/ngx-image-cropper/commit/0c9a2e489f370f0368f5758dcf829d5a9c9edf47

```
// Black 2x1 JPEG, with the following meta information set:
// - EXIF Orientation: 6 (Rotated 90° CCW)
// Source: https://github.com/blueimp/JavaScript-Load-Image
const testAutoOrientationImageURL =
    'data:image/jpeg;base64,/9j/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAYAAAA' +
    'AAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA' +
    'QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE' +
    'BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIAAEAAgMBEQACEQEDEQH/x' +
    'ABKAAEAAAAAAAAAAAAAAAAAAAALEAEAAAAAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAA' +
    'AAAAAEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwA/8H//2Q==';

export function supportsAutomaticRotation(): Promise<boolean> {
    return new Promise((resolve) => {
        const img = new Image();
        img.onload = () => {
            // Check if browser supports automatic image orientation:
            const supported = img.width === 1 && img.height === 2;
            resolve(supported);
        };
        img.src = testAutoOrientationImageURL;
    });
}
```

**Comment by perseon** [comment]
Hi,
A recent update on chrome on android broke the orientation. In March the jpegs had good orientation, now the jpegs are rotated 90deg anticlockwise. I've switched to @ssmithereens's fork, forced the exifOrientation override and it's working again. Didn't have time to investigate why. Also I should mention that only in chrome it's an issue. In brave browser for example it's working.

**Comment by davejm** [comment]
Thank you for everyone's input on this. I have released a new version (v2.2.0) that adds an 'autoRotate' option. It will only rotate the image according to EXIF orientation if this option is set to true and if the current browser does not support auto rotation natively.
Thanks @ssmithereens for raising this and @Junyan for the feature-detection snippet.

**Comment by derwaldgeist** [comment]
Here's an explanation why this happened:
https://stackoverflow.com/questions/61390195/exif-orientation-issue-in-safari-mobile/62248551#62248551

**Comment by alexcroox** [comment]
Is there a way to force orientation fixes regardless of the browser? My use case is resizing, fixing orientation, stripping Exif and sending to the server (stripping Exif to stop server attempting rotation). That way it will display the same on all browsers regardless when downloaded

**Comment by derwaldgeist** [comment]
Yes, I am doing it this way:
* https://github.com/mattiasw/ExifReader to get the EXIF information, then 
* https://github.com/blueimp/JavaScript-Load-Image to load the image from the file input to a canvas; not sure how this interoperates with `client-compress`, as I am not using it; I just found this issue when I was researching the EXIF problem
* rotate the canvas if required (rotation is an option of `load-image`); since this is dependent on whether the browser already does it automatically, have a look at this thread https://github.com/mattiasw/ExifReader/issues/99
* convert the image to a data URL using `canvas.toDataUrl()`
* https://github.com/blueimp/JavaScript-Canvas-to-Blob to conver the canvas back to a Blob
* uploading the Blob as an image payload to S3 (a Blob can be used like a file)

**Comment by alexcroox** [comment]
thanks @derwaldgeist, it's the "automatic rotation by the browser" that is throwing me. Ideally I don't care about the browser as I want to rotate then resize with canvas, stripping out any exif before saving/displaying in the browser. So in the end when it comes to the browser displaying it there will be no exif to juggle auto rotation (I guess that would be treated as orientation: 1). This way if I correct any orientation and strip any exif before uploading I won't ever need to worry about browser auto rotation when the altered image gets loaded from the server.

**Comment by alexcroox** [comment]
Thanks, Javascript-Load-Image library was the solution.
